NVDARemote/NVDARemote

- addon/globalPlugins/remoteClient/dialogs.py
self.SetSizerAndFit(sizer) was missing at the end of `ServerPanel.__init__()`
> fixes issue: Connect panel is visually broken when Server is selected.

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/dialogs.py
I've added translator comments to some strings (mostly UI-related and status messages) so translators can get an idea as to how to translate add-on messages. This prepares the add-on for localization. Thanks.
> Translator comments for add-on localization

- addon/globalPlugins/remoteClient/__init__.py
I have added a terminate method to the global plugin class to clean up and free resources. The addon should be able to reload without restarting NVDA.
> Added a terminate method

- addon/globalPlugins/remoteClient/server.py
I have edited the file server.py, and enclosed socket activity (send and receive) into try / except blocks. If an exception is raised, self.close() is called in the client who raised the exception. This is useful in slow connections, where timeout exceptions happen frequently.
> Handled exceptions that could happen in slow direct connections

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/dialogs.py
- addon/globalPlugins/remoteClient/serializer.py
- addon/globalPlugins/remoteClient/server.py
To avoid conflicts with other addons, the addon path is removed from sys.path after importing json module. I have performed this operation in __init__.py, dialogs.py, serializer.py and server.py.
> Removed addon path after importing json

- addon/globalPlugins/remoteClient/__init__.py
To match better the NVDA addon development specifications, I have changed get_config function in __init__.py. It now gets the config path from globalVars.appArgs.configPath, instead of config.getUserDefaultConfigPath()
> modified get_config function

- addon/locale/fa/LC_MESSAGES/nvda.po
The byte order mark causes msgfmt to fail compiling the translation and building
the addon to fail.  It's also useless for UTF-8 encoded files.
> Remove UTF-8 BOM from persian translation.

- addon/globalPlugins/remoteClient/__init__.py
Hi,
Sometimes NVDA throws PyDeadObjectError when terminating because menu object is already destroyed when NVDA Remote try to do so.
Adding a try block to pass PyDeadObjectError exception allows NVDARemote global plugin to be correctly terminated.
> Catch PyDeadObjectError exception in the terminate method

- addon/doc/en/readme.md
- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/dialogs.py
As requested in #39, in this pull request, the possibility to set the server port is added. For the client, it was already possible to connect to a remote server listening on another port using the "host:port" format.
> Add possibility to set the remote server port

- addon/doc/ca/readme.md
- addon/doc/en/readme.md
- addon/doc/es/readme.md
- addon/doc/es_CO/readme.md
- addon/doc/gl/readme.md
- addon/doc/nl/readme.md
Changed on all updated documentations < by &lt; and > by &gt; to make the navigators showing correctly the text surrounded by these symbols after converting markdown into HTML (now it only displays ":" in place of "<host>:<port>" or its respective translation).
Documentation for this change: https://daringfireball.net/projects/markdown/syntax > AUTOMATIC ESCAPING FOR SPECIAL CHARACTERS
Any problem please comment.
> Fixed markdown to html appearance problems: changed <> to &lt;&gt;

- addon/globalPlugins/remoteClient/__init__.py
I've been able to track #51 down. There was a bug in check_secure_desktop which returned False when there was no remote.ipc file available. Here is a pr. Since I removed the checking from check_secure_desktop, I also renamed that function. Checking is now done in the __init__ function for the GlobalPlugin.
> Do not auto-connect to configured control server on secure screens #51

- addon/globalPlugins/remoteClient/__init__.py
This will only happen when there is not a master or slave session already, so a relay connection should always take precedence. This fixes unexpected behaviour which I created in #95.
> Auto connect settings on secure desktops are respected again

- addon/globalPlugins/remoteClient/__init__.py
This fixes an issue where sd_server and sd_relay weren't properly destroyed (only closed) when leaving secure desktop. This caused an error upon leaving secure desktop when an instance of NVDA Remote had been used in slave mode. Cleaning up is good for everyone! :)
> Properly destroy sd_server and sd_relay when leaving secure desktop

- addon/globalPlugins/remoteClient/nvda_patcher.py
This is needed for ctrl+NVDA+r to work correctly.
Fixes #11
> Don't patch functions on the synth if synth is None

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/local_machine.py
- addon/globalPlugins/remoteClient/server.py
- addon/globalPlugins/remoteClient/session.py
- addon/globalPlugins/remoteClient/transport.py
Significant but backwards compatible changes to the remote protocol.
Now, each message which comes from a remote machine has an origin field containing its remote id.
When joining a channel, or when other machines join, these ids and their corresponding connection types are communicated.
This allows us to see exactly who is controlling what, and lays the groundwork for fixing several issues.
Specifically, this fixes #93 and lays the groundwork to be able to implement #65 and #67
> Protocol version 2

- addon/doc/en/readme.md
- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/bridge.py
- addon/globalPlugins/remoteClient/input.py
- addon/globalPlugins/remoteClient/local_machine.py
- addon/globalPlugins/remoteClient/nvda_patcher.py
- addon/globalPlugins/remoteClient/session.py
Here is a first attempt on implementing braille for NVDA Remote.
* Braille implementation is hook based, similar to speech and NVWave implementations. There were several reasons to drop the virtual braille display approach, particularly out of the box secure screens support.
* Both master and slave know about the braille display used at the other side of the connection
* When the slave uses braille and a master connects, the number of cells for the smallest display is used. When the slave uses no braille or another display with numCells=0, it's braille handler will be updated to use the master's numCells
* Braille input works as well. When sending keys, inputCore.manager.executeGesture is patched to send the gesture to the slave. We send gesture information as well as the path to the …
> Braille implementation for NVDA Remote

- addon/globalPlugins/remoteClient/dialogs.py
PR for #99:
Previously, Connect and Options dialogs were on the top-left portion of the screen. For consistency with other NVDA windows, center these dialogs. Thankfully, panels inside Connect dialog will also be centered on screen because wx.Dialog.Center will be used to center the whole dialog.
> Dialogs: center connect and options dialogs

- addon/globalPlugins/remoteClient/url_handler.py
This is needed so the URL handler can send WM_COPYDATA to NVDA, which is running at a higher integredy level due to UIAccess.
> Allow WM_COPYDATA through the window filter

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/beep_sequence.py
This adds a new function beep_sequence_async which calls beep_sequence in a thread, and changes the addon to use it.
This was done because beep_sequence is synchronous, and was used in functions which run in the main thread.
> Asynchronous beep sequence

- addon/globalPlugins/remoteClient/__init__.py
Not doing this created errors when reloading plugins
> Properly destroy the url handler window on plugin termination

- addon/globalPlugins/remoteClient/input.py
Braille input gestures didn't work when the slave was in browse mode, since we were just ignoring all the global commands due to a silly mistake I made. Now, only return a function if there is a real function to return, else continue the search for scripts
> Fix braille input gestures when slave is in browse mode (#136)

- addon/globalPlugins/remoteClient/__init__.py
IN disconnecting_as_master, we now check the existence of some objects before we try to do something with them, particularly menu items
> Fixed errors on plugin termination (#134)

- addon/globalPlugins/remoteClient/nvda_patcher.py
This adds support for nvaccess/nvda#7517 and is backwards compatible. Note that model specific gestures will already work in most cases, they won't work in case the model is retrieved using a AutoProperty style getter though.
> Support model specific braille display gestures

- addon/globalPlugins/remoteClient/input.py
Hi,
for a lot of time, as showed from #222, Braille has had problems in scrolling lines, for simple missed imports (baseObject in these sources, baseObject and vision in site hosted package).
This pr fixes it.
So, a new add-on release (with upgraded version to avoid confusion) would be very, very welcome.
> Fix imports for Braille

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/configuration.py
- addon/globalPlugins/remoteClient/dialogs.py
- addon/globalPlugins/remoteClient/transport.py
This PR addresses a critical, in my opinion, security vulnerability.
Currently the addon does not use SSL certificate hostname and CA chain to verify that user connects to a real server, not to one prepared by a hacker. It may result in Man in the Middle attack and practically excludes all the benefits of using encryption, on the contrary, it can create a very deceptive sense of security.
In this PR i am intending to write the following behavior:
1. If a certificate is a verified certificate, that is providing a correct CA chain and correct host name, it should be accepted,
2. If not, user should be prompted with a warning, also containing a certificate fingerprint and connection should continue when and only when user clearly accepts the risk.
3. Alternatively, user should be allowed to, …
> Add a SSL certificate hostname and CA chain verification

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/session.py
- addon/globalPlugins/remoteClient/transport.py
This way it's easier to tell which events may be subscribed to
> Use an explicit enum of transport events

- addon/globalPlugins/remoteClient/__init__.py
Hi All,
We sometimes need to use gestures to mute or unmute the speech coming from the remote computer,
However, the current status cannot be reported after the gesture is performed, and you can only check whether the item has been checked under the remote menu.
In addition, when using gestures to toggle mute or Unmute state of a remote computer, 'script_toggle_remote_mute' will be executed regardless of whether it is currently connected. This should not be the case.
I did all the above mentioned.
Thanks.
> Report when using gestures to mute or unmute the speech coming from the remote computer and prevent the use of gesture stoggle when not connected

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/bridge.py
This fixes access to the secure desktop, broken by #243.
In the bridge transport, we now check if the callback is an Enum and use its value.
Closes #270.
> Fix secure desktop support

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/transport.py
Before this, when switching to a secure desktop, you'd often (always?) miss the first output from NVDA, usually the UAC message.
This could be a little confusing.
This occurred because the connection took a short time to establish, but by then, NVDA had already reported the initial focus.
To get around this, block the main thread until the connection is established.
Since we're connecting to localhost, this should be pretty fast, but we use a 1 second timeout just in case.
This is a bit ugly, but I think it's cleaner and less risky than the alternative of queuing the output until the connection is established.
> Block the main thread when connecting on the secure desktop so we don't miss the first output.

- addon/globalPlugins/remoteClient/__init__.py
This was removed in nvaccess/nvda#12943, since NVDA 2022.1 is an API breaking release.
> Use shlobj.SHGetKnownFolderPath instead of (now removed) shlobj.SHGetFolderPath.

- addon/globalPlugins/remoteClient/__init__.py
- readme.md
When NVDA Remote starts, automatically try to parse the config and remove it if it fails to parse.
If the config fails to parse, nothing works, and you have to manually go in and remove it.
> Automatically remove corrupted configs

- .github/workflows/main.yml
Use version 3 of the checkout action, setup-python version 4, and set up and build with python 3.10.
Allow release creation and upload when a tag is created.
> Update GitHub action.

- addon/globalPlugins/remoteClient/__init__.py
- readme.md
Co-authored-by: @braillescreen
The gesture to open the connection dialog was originally done by @braillescreen, however the relevant places in the readme were not documented, so the pull request didn't merge. I documented the readme file correctly and replaced the __init__.py file with the version that was in the initial pull request and I think everything is correct and the PR is ready to merge.
Also, I want to point out that I didn't include anything in the changes section of the documentation because I don't know what the next version number will be, so the developers should include it in the changelog section.
@ctoth @tspivey Please let me know if anything needs to be done so I can commit before the PR is merged.
> Added a gesture to open the connection dialog and properly documented … the required locations in the readme file for this new gesture

- .github/workflows/main.yml
Prior workflow runs on tag creation will have to be manually run, this updates the workflow to run automatically when tags are created and pushed.
> Run workflow automatically on tag creation.

- readme.md
In the newest documentation update for the previous related PR, the instructions for quickly opening the connect dialogue (I.E. NVDA + Alt + Page UP) was only included in the second set of instructions, not the first set. This PR fixes this problem.
> readme.md: Fix new quick connect command not being in the top set of instructions.

- addon/globalPlugins/remoteClient/__init__.py
When the connection is interrupted, the hook thread isn't terminated. Previously, when the connection was restored, a new hook thread was created without terminating the old one, resulting in abandoned hook threads. Now, we only create a new hook thread when connecting if there isn't a hook thread already.
I discovered this while looking into #290, which I see occasionally. I don't really see how this could cause that. However, when I see #290, it does seem like my keyboard gets trapped sometimes, which made me a bit suspicious of the hook thread. In any case, I think correctness is not a bad thing when messing with hooks. :)
> Don't create a new keyboard hook thread if there already is one.

- addon/globalPlugins/remoteClient/transport.py
Previously, if we reconnected because the server disconnected, everything was fine. However, if we reconnected because of a socket error, NVDA often froze when the user eventually tried to disconnect. One way to reproduce this was to turn on airplane mode while using WiFi, wait for disconnection, turn off airplane mode, wait for reconnection, then manually disconnect.
Here's what was happening:
1. When a socket error happened, we broke out of the loop in TCPTransport.run.
2. We set self.disconnected to False and called self._disconnect.
3. self._disconnect checked self.disconnected. Since it was False, it just returned early, doing nothing.
4. That meant that the queue thread was never terminated.
5. Upon reconnection, we created a new queue thread, even though the old one was still …
> Fix freeze when disconnecting after a reconnection due to a socket error.

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/local_machine.py
- addon/globalPlugins/remoteClient/nvda_patcher.py
- addon/globalPlugins/remoteClient/session.py
- buildVars.py
This commit removes legacy code paths that supported NVDA versions before 2023.1,
simplifying the codebase by:
- Removing all version-specific code branches and checks for pre-2023.1 versions
- Using modern NVDA event registration APIs exclusively:
- braille.decide_enabled
- braille.displayChanged
- braille.displaySizeChanged
- tones.decide_beep
- nvwave.decide_playWaveFile
- braille.pre_writeCells
- inputCore.decide_executeGesture
- Removing deprecated direct handler patching for braille and input
- Updating minimum supported NVDA version to 2023.1 in buildVars.py
This change reduces technical debt and maintenance burden while leveragingNVDA's more robust modern APIs. Users on older NVDA versions should use older versions of NVDA Remote.
> Remove support for NVDA versions prior to 2024.1

- addon/globalPlugins/remoteClient/__init__.py
Replace old-style __doc__ string assignments and __gestures dictionary with
modern @script decorators. This change:
- Improves code readability by co-locating gestures with their functions
- Uses standard NVDA decorator pattern for script documentation
- Maintains existing functionality while modernizing the codebase
Affected commands:
- Toggle remote mute
- Push clipboard (ctrl+shift+NVDA+c)
- Copy link
- Connect (alt+NVDA+pageUp)
- Disconnect (alt+NVDA+pageDown)
> refactor: migrate to @script decorators for NVDA commands

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/protocol.py
- addon/globalPlugins/remoteClient/secureDesktop.py
- addon/globalPlugins/remoteClient/serializer.py
- addon/globalPlugins/remoteClient/server.py
- addon/globalPlugins/remoteClient/session.py
- addon/globalPlugins/remoteClient/transport.py
This pr introduces a typed approach to handling message types in the remote client by:
1. Adding a new RemoteMessageType enum in protocol.py to centralize all message type constants
2. Refactoring message sending code across the codebase to use the enum instead of string literals
3. Updating the JSONSerializer to handle Enum types by extracting their values
4. Adding type hints to support both string and Enum types in relevant functions
5. Creating an abstract Serializer base class to formalize the serialization interface
Key changes:
- Replaced hardcoded strings like 'set_clipboard_text', 'key', 'ping', etc. with enum values
- Updated serializer.py to properly handle Enum types in the type parameter
- Modified message sending code in __init__.py, server.py, session.py, and transport.py
- …
> Replace string message types with enum

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/bridge.py
- addon/globalPlugins/remoteClient/client.py
- addon/globalPlugins/remoteClient/configuration.py
- addon/globalPlugins/remoteClient/local_machine.py
- addon/globalPlugins/remoteClient/menu.py
- addon/globalPlugins/remoteClient/secureDesktop.py
- addon/globalPlugins/remoteClient/session.py
- addon/globalPlugins/remoteClient/transport.py
Splits NVDA Remote's core functionality into a dedicated `RemoteClient` class, moving most logic out of `GlobalPlugin`. The key changes:
- Created `RemoteClient` to handle all the connection/session/keyboard management that was tangled up in `GlobalPlugin`
- `GlobalPlugin` now just maps NVDA scripts to `RemoteClient` methods and handles initialization
- Switched connection handling to use proper `ConnectionInfo` objects instead of (host, port) tuples
- Added `RelayTransport.create()` factory to centralize transport setup
- Fixed up secure desktop connections to use `ConnectionInfo` 
- Added proper `close()` cleanup to sessions
Made `Menu` smarter about connection states and fixed some menu item lifecycle issues.
The diff looks big but it's mostly moving code - the core functionality …
> Split Client

- addon/globalPlugins/remoteClient/connection_info.py
- addon/globalPlugins/remoteClient/nvda_patcher.py
- addon/globalPlugins/remoteClient/session.py
- addon/globalPlugins/remoteClient/transport.py
This PR moves NVDA Remote's sound and speech event handling from the patcher layer to use NVDA's native extension points directly. This simplifies the code and removes a layer of indirection.
- Added `RemoteExtensionPoint` class to bridge NVDA extension points to remote messages 
- Moved speech, tone, and wave file events to use extension points directly instead of going through the patcher
- Events now flow: NVDA extension point -> Remote message -> Remote peer, instead of the previous: NVDA -> Patcher -> Callback -> Remote message -> Remote peer
- Removed redundant code in wave file handling and speech management
- Cleaned up imports and unused code
- Simpler architecture - removes an unnecessary layer of event handling
- More reliable - uses NVDA's built-in extension points instead of …
> Outbound Remote Extension Points
