- addon/locale/nl/lc_messages/nvda.po
I just translated NVDA Remote to Dutch, feel free to merge this.
> Dutch translation

- addon/locale/hr/lc_messages/nvda.po
this is a croatian localization for NVDAREMOTE addon
> added croatian localization for nvda remote

- addon/locale/es/lc_messages/nvda.po
I have updated the spanish translation with the two new strings related to the mute / unmute script.
> Updated spanish translation

- addon/locale/fa/LC_MESSAGES/nvda.po
some problems has been fixed.
modified:   addon/locale/fa/LC_MESSAGES/nvda.po
> updated persian translation

- addon/doc/es/readme.md
- addon/locale/es/LC_MESSAGES/nvda.po
I have updated the spanish translation to be more consistent and user-friendly, because some users have requested that in the NVDA spanish mailing list.
> Fixed some errors in spanish translation

- addon/doc/gl/readme.md
- addon/locale/gl/LC_MESSAGES/nvda.po
Added galician translation, created by Ivan Novegil
> Added galician translation

- addon/doc/fr/Readme.md
- addon/locale/fr/LC_MESSAGES/nvda.po
Hi,
Michel Such and me have updated French documentation and interface to fix some typo and change some terms.
We reviewed it with others members of the NVDA French translation team.
> Updated french translation

- addon/doc/es_CO/readme.md
- addon/locale/es_CO/LC_MESSAGES/nvda.po
Added colombian spanish translation created by Slann Tonic
> Added colombian spanish translation

- addon/doc/it/readme.md
- addon/locale/it/lc_messages/nvda.po
Italian translation contributed by ChrisLeo from NVDA-translations mailing list.
> Italian translation contributed by ChrisLeo from NVDA-translations

- addon/doc/pl/readme.md
Sorry for the inconvenience, but previous recoding by Chris was broken, and my initial commit was in cp1250 (default setting of notepad2, which I forgot to change).
> Pl readme properly encoded to utf8 from cp1250.

- addon/doc/ca/readme.md
- addon/locale/ca/LC_MESSAGES/nvda.po
Added catalan translation by Jordi Nogal
> Added catalan translation

- addon/doc/sk/readme.md
- addon/locale/sk/lc_messages/nvda.po
It's complete and known to build. As the new string appear we will be able to update it with @ondrosik
> Initial attempt at slovak translation

- addon/doc/gl/readme.md
- addon/locale/gl/LC_MESSAGES/nvda.po
Updated message host as in spanish translation.
Update: on thursday 26th, commited the updates of the documentation and included in this pull request.
> Updated galician translation (minor changes)

- addon/globalPlugins/remoteClient/__init__.py
I have fixed some bugs which caused the user loosing control on a remote machine when a secure screen was displayed, specially on logon screens after rebooting the machine or loging off from a session.
I have tested these changes on a virtual machine before commiting them. The addon now apparently works as expected, with the bugs fixed.
> Some bugs fixed in secure desktops.

- addon/globalPlugins/remoteClient/__init__.py
- addon/locale/es/LC_MESSAGES/nvda.po
This pull request has 2 commits. In the first, the disconnect hotkey can now be changed from the NVDA input gestures dialog. Additional gestures can be added to disconnect a remote session too.
In the second commit, the spanish translation has been updated.
> The disconnect gesture can be changed from NVDA input gestures dialog

- addon/locale/gl/LC_MESSAGES/nvda.po
The galician translation was updated including the last strings added to the source code. Changelog:
-Disconnect a remote session - Desconectar dunha sesión remota.
If there's any problem, contact me.
> Updated galician translation.

- addon/locale/nl/LC_MESSAGES/nvda.po
This branch contains new translations for added strings.
> Update dutch translation

- addon/doc/fr/Readme.md
- addon/locale/fr/LC_MESSAGES/nvda.po
Hi,
We have updated the documentation to reflect new version number, and added the translation for the disconnect gesture description.
Authors: Michel Such, Bachir Benanou, Rémy Ruiz and me.
Thanks.
> Update French translation and update version number in the documentation

- addon/doc/en/readme.md
- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/dialogs.py
> Added the ability to self-host the control server.

- addon/globalPlugins/remoteClient/__init__.py
> Change f11 to a gesture

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/local_machine.py
Also renamed the menu item to Mute Remote since it mutes both speech and sounds.
Fixes #52
> Have muting also apply to remote sounds

- addon/doc/es/readme.md
- addon/locale/es/LC_MESSAGES/nvda.po
This pull request has 3 commits, but one of them is a merge from the original repo. In the other 2 commits, the spanish translation and documentation have been updated.
> Updated spanish localization

- addon/doc/ca/readme.md
- addon/doc/es_CO/readme.md
- addon/locale/ca/LC_MESSAGES/nvda.po
- addon/locale/es_CO/LC_MESSAGES/nvda.po
This pull request has 4 commits, one per file. I have updated the catalan and colombian spanish translations and documentation.
> Updated catalan and colombian spanish localizations

- addon/doc/en/readme.md
- addon/doc/nl/readme.md
- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/dialogs.py
With this pull request, it is possible to auto connect to a local or remote server in controlling mode.
Nb. Posted on behalf of @babbagecom
> Allow auto-connect to control server in master mode #88

- addon/globalPlugins/remoteClient/dialogs.py
Also fix another bug where all the messages related to port checking had variables in upper case.
> Updated the portcheck check to point at portcheck.nvdaremote.com

- addon/locale/hr/LC_MESSAGES/nvda.po
- addon/locale/pl/LC_MESSAGES/nvda.po
zstaneci@ updated polish and croatian translations of the addon.
> nvda remote transllation

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/session.py
Add a menu option and script to copy a link suitable for sharing to the clipboard.
Closes #114
> Add copy link

- addon/doc/fi/readme.md
- addon/locale/fi/LC_MESSAGES/nvda.po
User interface messages and documentation are both translated.
> Add Finnish translation

- addon/globalPlugins/remoteClient/__init__.py
> When hosting a relay server, close it before transport (#107)

- addon/locale/he/LC_MESSAGES/nvda.po
- addon/locale/he/manifest.ini
- addon/locale/hr/LC_MESSAGES/nvda.po
- addon/locale/pl/LC_MESSAGES/nvda.po
hr update and final pull request... dam the git for ever
> updated croatian, hebrew and polish translations

- addon/globalPlugins/remoteClient/__init__.py
This is bound to CTRL+Shift+NVDA+C by default
> Add a script to push the clipboard

- addon/globalPlugins/remoteClient/__init__.py
> Check braille.handler._messageCallLater before calling Stop()

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/dialogs.py
Closes #171
See nvaccess/nvda#7104 and nvaccess/nvda#8084
> Support for WX Python Phoenix

- addon/doc/de/readme.md
- addon/locale/de/LC_MESSAGES/nvda.po
German translation update of user interface strings and documentation.
> German translation update

- addon/doc/es/readme.md
- addon/doc/gl/readme.md
- addon/locale/es/LC_MESSAGES/nvda.po
- addon/locale/gl/LC_MESSAGES/nvda.po
1. Updated Spanish localization and documentation with new strings and changelog entry. Thanks to @jmdaweb for his original work.
2. Updated Galician localization and documentation with new strings and changelog entry. Reviewed full documentation to adapt it to the normative lexic and to correct several mistakes.
If any problem please comment.
> Updated Spanish and Galician translations

- addon/doc/pt_PT/readme.md
- addon/locale/pt_PT/LC_MESSAGES/nvda.po
Added portuguese (Portugal) interface and documentation, contributed by Angelo Miguel Abrantes.
> Added portuguese (Portugal) localization

- addon/doc/ro/readme.md
- addon/locale/ro/lc_messages/nvda.po
Hello, I've translated the add-on into Romanian, as many people in the NVDA Romanian Community use it. I will add the translation of readme.md soon.
> Added the translation into Romanian

- addon/locale/sr/LC_MESSAGES/nvda.po
Updated the Serbian interface and translated missing options.
> Updated Serbian translation.

- addon/globalPlugins/remoteClient/__init__.py
Signed-off-by: Peter Vágner <pvdeejay@gmail.com>
> Don't verify TLS certificate when connecting to 127.0.0.1 (fixes #251)

- addon/globalPlugins/remoteClient/dialogs.py
It allows accepting certificate fingerprint similar to when connecting for real. It fixes #244.
Signed-off-by: Peter Vágner <pvdeejay@gmail.com>
> Improve key generation on server

- addon/locale/sk/LC_MESSAGES/nvda.po
Signed-off-by: Peter Vágner <pvdeejay@gmail.com>
> Updated slovak language file

- addon/doc/tr/readme.md
- addon/locale/tr/lc_messages/nvda.po
Translations for the Turkish language by @surveyor123
> Add Turkish translations

- addon/locale/sr/LC_MESSAGES/nvda.po
Updated the Serbian interface translation.
> Updated Serbian translation

- addon/globalPlugins/remoteClient/transport.py
1. Reading/writing from an SSL socket is not thread safe, so protect it using a lock.
2. select operates on the raw socket, which means that it might report there is data to be read but there is no actual data for us.
Use non-blocking reads to deal with this.
These changes fix spurious intermittent connection dropouts which were occurring in some cases.
> SSL socket fixes to improve connection stability.

- addon/locale/hr/LC_MESSAGES/nvda.po
- addon/locale/pl/LC_MESSAGES/nvda.po
Updated polish and croatian translations,
compatible to all commits in the branch.
Can you make the maintenance release?
@ctoth 
@tspivey
> updated croatian and polish,

- addon/globalPlugins/remoteClient/local_machine.py
- addon/globalPlugins/remoteClient/nvda_patcher.py
- addon/globalPlugins/remoteClient/session.py
it is now possible to pause remote speech
> Implement pausing remote speech

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/dialogs.py
> Replaced host Editbox to Editable combobox to display last connections.

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/local_machine.py
- addon/globalPlugins/remoteClient/nvda_patcher.py
- addon/globalPlugins/remoteClient/session.py
- buildVars.py
Implement support for the 2023 extension points. At least a draft until https://github.com/nvaccess/nvda/pull/14536 is merged.
> Support NVDA 2023.1

- .gitignore
- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/beep_sequence.py
- addon/globalPlugins/remoteClient/bridge.py
- addon/globalPlugins/remoteClient/callback_manager.py
- addon/globalPlugins/remoteClient/configuration.py
- addon/globalPlugins/remoteClient/connection_info.py
- addon/globalPlugins/remoteClient/cues.py
- addon/globalPlugins/remoteClient/dialogs.py
- addon/globalPlugins/remoteClient/input.py
- addon/globalPlugins/remoteClient/keyboard_hook.py
- addon/globalPlugins/remoteClient/local_machine.py
- addon/globalPlugins/remoteClient/nvda_patcher.py
- addon/globalPlugins/remoteClient/serializer.py
- addon/globalPlugins/remoteClient/session.py
- addon/globalPlugins/remoteClient/transport.py
- addon/globalPlugins/remoteClient/url_handler.py
This PR makes several changes to improve code style consistency and readability in the NVDA Remote addon. The changes follow NVDA's code style guidelines.
- Added type hints for key attributes and parameters
- Improved docstrings for classes and methods
- Added class-level type annotations for important attributes
Converted snake_case to mixedCase for consistency with NVDA style:
**Session Management:**
- `slave_session` → `slaveSession`
- `master_session` → `masterSession` 
- `local_machine` → `localMachine`
**Transport Layer:**
- `master_transport` → `masterTransport`
- `slave_transport` → `slaveTransport`
**Thread/Process Management:**
- `sending_keys` → `sendingKeys`
- `hook_thread` → `hookThread`
**Secure Desktop:**
- `sd_server` → `sdServer`
- `sd_relay` → `sdRelay` 
- `sd_bridge` → …
> Code Style Improvements

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/beep_sequence.py
- addon/globalPlugins/remoteClient/bridge.py
- addon/globalPlugins/remoteClient/callback_manager.py
- addon/globalPlugins/remoteClient/dialogs.py
- addon/globalPlugins/remoteClient/keyboard_hook.py
- addon/globalPlugins/remoteClient/local_machine.py
- addon/globalPlugins/remoteClient/nvda_patcher.py
- addon/globalPlugins/remoteClient/serializer.py
- addon/globalPlugins/remoteClient/server.py
- addon/globalPlugins/remoteClient/session.py
- addon/globalPlugins/remoteClient/transport.py
This commit adds static type hints throughout the NVDA Remote codebase to improve code clarity, catch potential bugs, and enable better IDE support. Key changes include:
Transport & Networking:
- Add complete type annotations to TCPTransport and RelayTransport classes
- Type socket handling and SSL connection management
- Add typing for the callback registration system
- Properly type address tuples and connection parameters
Session Management:
- Add typing for RemoteSession, MasterSession and SlaveSession
- Type all session state tracking and configuration
- Add proper types for speech/braille data structures
- Type the patch callback system
Server Implementation:
- Refactor Server class to LocalRelayServer for clarity
- Add comprehensive typing for server socket handling
- Type client …
> Add comprehensive type annotations

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/menu.py
- **refactor: Extract menu logic into separate RemoteMenu class**
- **feat: Add comprehensive type hints to RemoteMenu class**
> UI Simplification

- addon/globalPlugins/remoteClient/__init__.py
- addon/globalPlugins/remoteClient/secureDesktop.py
This PR refactors our secure desktop handling functionality by extracting it into a dedicated module and introducing a new `SecureDesktopHandler` class. This change improves code organization, type safety, and maintainability while maintaining full compatibility with existing functionality.
- Create new `secureDesktop.py` module to handle secure desktop transitions
- Introduce `SecureDesktopHandler` class to encapsulate secure desktop logic
- Add comprehensive type hints and documentation
- Improve resource cleanup and error handling
- Use modern Python features (dataclasses, pathlib) for better code structure
- `SecureDesktopHandler`: Core class managing secure desktop transitions
- `SecureDesktopConnection`: Dataclass for connection details
- Improved path handling using `pathlib.Path` …
> refactor: Extract secure desktop handling into dedicated module

- sconstruct
- site_scons/site_tools/gettexttool/__init__.py
This upgrades the addon template to commit 2f4ba1ec0ab7eb3a0bbb8fb7a9be0c6459ac09e0.
> Upgrade addon template

- addon/globalPlugins/remoteClient/session.py
- Centralize patch callback handling in RemoteSession base class
- Move client connection/disconnection logic to base class
- Improve type safety:
- Replace string-based mode with ConnectionMode enum
- Add proper typing for client parameter in handleClientConnected
- Remove unused Union type import
- Clean up legacy code:
- Remove obsolete index handling from 2019.3
- Remove unused versionInfo import
- Remove redundant handleConnected/Disconnected methods
- Fix code organization:
- Move clipboard handler registration to base class
- Move common event registrations to base class
- Remove duplicated callback registration code
- Fix naming inconsistency of MOTD vs Motd method names
- Remove dataclass import since it's not used
> refactor: improve session
